Repository spree/spree, pull requests merged in 2019-10, with the labels that each got.

#9572 Added caching for JSON LD structured data
  frontend/app/helpers/spree/structured_data_helper.rb
Labels: Frontend

#9561 Docs/spree 4 0 final release notes
  README.md
  cmd/lib/spree_cmd/templates/extension/Appraisals
  cmd/lib/spree_cmd/templates/extension/gemfiles/spree_4_0.gemfile
  core/lib/spree/core/version.rb
  guides/src/content/developer/upgrades/three-dot-seven-to-four-dot-oh.md
  guides/src/content/release_notes/0_10_0.md
  guides/src/content/release_notes/0_30_0.md
  guides/src/content/release_notes/0_40_0.md
  guides/src/content/release_notes/0_50_0.md
  guides/src/content/release_notes/0_60_0.md
  guides/src/content/release_notes/0_70_0.md
  guides/src/content/release_notes/0_9_0.md
  guides/src/content/release_notes/1_0_0.md
  guides/src/content/release_notes/1_1_0.md
  guides/src/content/release_notes/1_1_4.md
  guides/src/content/release_notes/1_2_0.md
  guides/src/content/release_notes/1_2_2.md
  guides/src/content/release_notes/1_3_0.md
  guides/src/content/release_notes/2_0_0.md
  guides/src/content/release_notes/2_1_0.md
  guides/src/content/release_notes/2_2_0.md
  guides/src/content/release_notes/2_3_0.md
  guides/src/content/release_notes/2_4_0.md
  guides/src/content/release_notes/3_0_0.md
  guides/src/content/release_notes/3_1_0.md
  guides/src/content/release_notes/3_2_0.md
  guides/src/content/release_notes/3_3_0.md
  guides/src/content/release_notes/3_4_0.md
  guides/src/content/release_notes/3_5_0.md
  guides/src/content/release_notes/3_6_0.md
  guides/src/content/release_notes/3_7_0.md
  guides/src/content/release_notes/4_0_0.md
Labels: Documentation :book:

#9567 Add Store Filter to Payment method
  backend/app/controllers/spree/admin/payment_methods_controller.rb
  backend/app/views/spree/admin/payment_methods/_form.html.erb
  backend/spec/features/admin/configuration/payment_methods_spec.rb
  core/app/models/spree/order.rb
  core/app/models/spree/payment_method.rb
  core/app/models/spree/store.rb
  core/db/migrate/20191005121504_add_store_id_to_payment_methods.rb
  core/spec/models/spree/order_spec.rb
  frontend/app/views/spree/checkout/_payment.html.erb
  frontend/spec/features/checkout_spec.rb
Labels: Admin Panel ⚙️, Frontend, New Feature :tada:

#9585 Added Spree 4.1 to CHANGELOG
  CHANGELOG.md
  guides/src/content/developer/upgrades/four-dot-oh-to-four-dot-one.md
  guides/src/content/release_notes/4_1_0.md
Labels: Documentation :book:

#9587 [skip CI] Update getting started guide for Spree 4.0
  guides/src/content/developer/tutorials/getting_started_tutorial.md
Labels: Documentation :book:

#9377 Fix local links urls in Guides
  guides/gatsby-node.js
  guides/src/components/Section.js
  guides/src/pages/api/v2/index.js
  guides/src/utils/openApiNav.js
Labels: Documentation :book:

#9607 Update base_helper for new design
  core/app/helpers/spree/base_helper.rb
  core/config/locales/en.yml
Labels: Frontend

#9613 Move orders controller from spree designs
  frontend/app/controllers/spree/orders_controller.rb
Labels: Frontend

#9608 Move seeds from spree designs
  .codeclimate.yml
  core/db/default/spree/stores.rb
  sample/db/samples/adjustments.rb
  sample/db/samples/assets.rb
  sample/db/samples/option_types.rb
  sample/db/samples/option_values.rb
  sample/db/samples/orders.rb
  sample/db/samples/product_option_types.rb
  sample/db/samples/product_properties.rb
  sample/db/samples/products.rb
  sample/db/samples/promotions.rb
  sample/db/samples/properties.rb
  sample/db/samples/prototypes.rb
  sample/db/samples/return_authorization_reasons.rb
  sample/db/samples/stock.rb
  sample/db/samples/tax_categories.rb
  sample/db/samples/tax_rates.rb
  sample/db/samples/taxonomies.rb
  sample/db/samples/taxons.rb
  sample/db/samples/variants.csv
  sample/db/samples/variants.rb
  sample/db/samples/zones.rb
  sample/lib/spree_sample.rb
Labels: Frontend

#9616 Add inline_svg as a Spree dependency
  frontend/spree_frontend.gemspec
Labels: Frontend

#9615 Fix variant positions in admin panel
  backend/app/assets/javascripts/spree/backend/admin.js
  backend/app/controllers/spree/admin/resource_controller.rb
Labels: Admin Panel ⚙️, javascript
