Repository spree/spree, pull requests merged in 2019-11, with the labels that each got.

#9617 Use correct values for colors in OptionValue seeds
  core/app/models/spree/variant.rb
  core/app/presenters/spree/variants/options_presenter.rb
  core/spec/models/spree/variant_spec.rb
  core/spec/presenters/spree/variants/options_presenter_spec.rb
  sample/db/samples/variants.rb
Labels: Frontend

#9622 [SD-463] Move seo_url method to spree from spree-designs
  core/app/helpers/spree/base_helper.rb
Labels: Frontend

#9610 Spree Core docs updates
  guides/gatsby-config.js
  guides/src/content/developer/core/addresses.md
  guides/src/content/developer/core/inventory.md
  guides/src/content/developer/core/payments.md
  guides/src/content/developer/core/products.md
  guides/src/content/developer/core/promotions.md
  guides/src/content/developer/core/shipments.md
  guides/src/content/developer/core/taxation.md
  guides/src/content/release_notes/1_3_0.md
  guides/src/content/release_notes/2_1_0.md
  guides/src/content/release_notes/4_0_0.md
Labels: Documentation :book:

#9627 Add "Table of Contents" to Guides
  guides/src/components/Header.js
  guides/src/components/Layout.js
  guides/src/components/NavItem.js
  guides/src/components/Toc.js
  guides/src/components/helpers/Alert.js
  guides/src/styles/app.css
  guides/src/templates/guide.js
Labels: Documentation :book:

#9632 [Guides] Open "Edit this page on Github" link in tab/window
  guides/src/components/MarkdownPageFooter.js
Labels: Documentation :book:

#9641 Add inline_svg require
  frontend/lib/spree/frontend.rb
Labels: Frontend

#9642 Move presenters to spree core
  core/app/presenters/spree/product_summary_presenter.rb
  core/app/presenters/spree/variant_presenter.rb
  core/app/presenters/spree/variants/option_types_presenter.rb
  core/spec/presenters/spree/variant_presenter_spec.rb
  core/spec/presenters/spree/variants/option_types_presenter_spec.rb
Labels: Frontend

#9640 Move images to spree core
  frontend/app/assets/images/arrow-right.svg
  frontend/app/assets/images/arrow.svg
  frontend/app/assets/images/bag.svg
  frontend/app/assets/images/burger.svg
  frontend/app/assets/images/check-mark-circle.png
  frontend/app/assets/images/check-mark-circle.svg
  frontend/app/assets/images/check-mark.svg
  frontend/app/assets/images/circle.svg
  frontend/app/assets/images/close.svg
  frontend/app/assets/images/edit.svg
  frontend/app/assets/images/empty-cart.svg
  frontend/app/assets/images/error.svg
  frontend/app/assets/images/facebook.svg
  frontend/app/assets/images/full_circle.svg
  frontend/app/assets/images/garbage.svg
  frontend/app/assets/images/garbage_2.svg
  frontend/app/assets/images/instagram.svg
  frontend/app/assets/images/logo-spree.png
  frontend/app/assets/images/logo.png
  frontend/app/assets/images/logo.svg
  frontend/app/assets/images/logo@2x.png
  frontend/app/assets/images/logo@3x.png
  frontend/app/assets/images/magnifying-glass.svg
  frontend/app/assets/images/minus.svg
  frontend/app/assets/images/noimage/plp.png
  frontend/app/assets/images/person.svg
  frontend/app/assets/images/picture-zoom.svg
  frontend/app/assets/images/plus.svg
  frontend/app/assets/images/radio-button.svg
  frontend/app/assets/images/search-no-results.svg
  frontend/app/assets/images/search.svg
  frontend/app/assets/images/twitter.svg
  frontend/app/assets/images/vimeo.svg
  frontend/config/initializers/assets.rb
Labels: Frontend

#9639 9638 - jsTree quickfix
  backend/app/assets/javascripts/spree/backend/taxonomy.js
Labels: Admin Panel ⚙️

#9645 Feature/new designs finders
  core/app/finders/spree/variants/option_types_finder.rb
  core/app/finders/spree/variants/visible_finder.rb
  core/spec/finders/spree/products/find_spec.rb
  core/spec/finders/spree/variants/option_types_finder_spec.rb
  core/spec/finders/spree/variants/visible_finder_spec.rb
Labels: Frontend

#9649 Add placeholder images
  frontend/app/assets/images/homepage/men.jpg
  frontend/app/assets/images/homepage/men_mobile.jpg
  frontend/app/assets/images/homepage/men_tablet_landscape.jpg
  frontend/app/assets/images/homepage/men_tablet_portrait.jpg
  frontend/app/assets/images/homepage/sportswear.jpg
  frontend/app/assets/images/homepage/sportswear_mobile.jpg
  frontend/app/assets/images/homepage/sportswear_tablet_landscape.jpg
  frontend/app/assets/images/homepage/sportswear_tablet_portrait.jpg
  frontend/app/assets/images/homepage/streetstyle.jpg
  frontend/app/assets/images/homepage/streetstyle_mobile.jpg
  frontend/app/assets/images/homepage/streetstyle_tablet_landscape.jpg
  frontend/app/assets/images/homepage/streetstyle_tablet_portrait.jpg
  frontend/app/assets/images/homepage/summer_collection.jpg
  frontend/app/assets/images/homepage/summer_collection_mobile.jpg
  frontend/app/assets/images/homepage/summer_collection_tablet_landscape.jpg
  frontend/app/assets/images/homepage/summer_collection_tablet_portrait.jpg
  frontend/app/assets/images/homepage/summersale.jpg
  frontend/app/assets/images/homepage/summersale_mobile.jpg
  frontend/app/assets/images/homepage/summersale_tablet_landscape.jpg
  frontend/app/assets/images/homepage/summersale_tablet_portrait.jpg
  frontend/app/assets/images/homepage/women.jpg
  frontend/app/assets/images/homepage/women_mobile.jpg
  frontend/app/assets/images/homepage/women_tablet_landscape.jpg
  frontend/app/assets/images/homepage/women_tablet_portrait.jpg
  frontend/app/assets/images/noimage/big_category_banner.jpg
  frontend/app/assets/images/noimage/big_category_banner_mobile.jpg
  frontend/app/assets/images/noimage/big_category_banner_tablet_landscape.jpg
  frontend/app/assets/images/noimage/big_category_banner_tablet_portrait.jpg
  frontend/app/assets/images/noimage/category_banner.jpg
  frontend/app/assets/images/noimage/category_banner_mobile.jpg
  frontend/app/assets/images/noimage/category_banner_plp.jpg
  frontend/app/assets/images/noimage/category_banner_tablet_landscape.jpg
  frontend/app/assets/images/noimage/category_banner_tablet_portrait.jpg
  frontend/app/assets/images/noimage/main_banner.jpg
  frontend/app/assets/images/noimage/main_banner_mobile.jpg
  frontend/app/assets/images/noimage/main_banner_tablet_landscape.jpg
  frontend/app/assets/images/noimage/main_banner_tablet_portrait.jpg
  frontend/app/assets/images/noimage/product_photo.jpg
  frontend/app/assets/images/noimage/promo_banner.jpg
  frontend/app/assets/images/noimage/promo_banner_megamenu.jpg
  frontend/app/assets/images/noimage/promo_banner_mobile.jpg
  frontend/app/assets/images/noimage/promo_banner_tablet_landscape.jpg
  frontend/app/assets/images/noimage/promo_banner_tablet_portrait.jpg
  frontend/config/initializers/assets.rb
Labels: Frontend

#9648 Move translations from spree design
  api/spec/requests/spree/api/v2/storefront/checkout_spec.rb
  core/config/locales/en.yml
Labels: Frontend
