Repository spree/spree, pull requests merged in 2020-05, with the labels that each got.

#10136 Fixes requesting products from multiple taxon in API v2
  core/app/finders/spree/products/find.rb
  core/spec/finders/spree/products/find_spec.rb
Labels: API

#10128 [SD-263] Spree::Store fields for footer info
  backend/app/views/spree/admin/stores/_form.html.erb
  backend/spec/features/admin/store_spec.rb
  core/config/locales/en.yml
  core/db/migrate/20200430072209_add_footer_fields_to_spree_stores.rb
  core/lib/spree/permitted_attributes.rb
  core/spec/models/spree/store_spec.rb
  frontend/app/views/spree/shared/_footer.html.erb
  frontend/spec/features/store_spec.rb
Labels: Admin Panel ⚙️, Storefront :shopping_cart:

#10105 [SD-234] Crossed out compare at price
  backend/app/views/spree/admin/products/_form.html.erb
  backend/app/views/spree/admin/variants/_form.html.erb
  backend/spec/features/admin/products/edit/variants_spec.rb
  backend/spec/features/admin/products/products_spec.rb
  core/app/helpers/spree/base_helper.rb
  core/app/models/concerns/spree/default_price.rb
  core/app/models/spree/price.rb
  core/app/models/spree/product.rb
  core/app/models/spree/variant.rb
  core/app/presenters/spree/variant_presenter.rb
  core/config/locales/en.yml
  core/db/migrate/20200421095017_add_compare_at_amount_to_spree_prices.rb
  core/lib/spree/permitted_attributes.rb
  core/spec/models/spree/price_spec.rb
  frontend/app/assets/javascripts/spree/frontend/views/spree/products/cart_form.js
  frontend/app/assets/stylesheets/spree/frontend/views/spree/products/cart_form.scss
  frontend/app/views/spree/products/_cart_form.html.erb
  frontend/spec/features/products_spec.rb
Labels: Admin Panel ⚙️, Storefront :shopping_cart:

#9415 Multi Currency Improvements
  api/app/controllers/concerns/spree/api/v2/storefront/order_concern.rb
  api/app/helpers/spree/api/api_helpers.rb
  api/spec/controllers/spree/api/v1/stores_controller_spec.rb
  api/spec/requests/spree/api/v2/storefront/cart_spec.rb
  backend/app/assets/javascripts/spree/backend.js
  backend/app/assets/javascripts/spree/backend/admin.js
  backend/app/assets/javascripts/spree/backend/multi_currency.js
  backend/app/controllers/spree/admin/general_settings_controller.rb
  backend/app/controllers/spree/admin/prices_controller.rb
  backend/app/controllers/spree/admin/stores_controller.rb
  backend/app/views/spree/admin/general_settings/_form.html.erb
  backend/app/views/spree/admin/general_settings/edit.html.erb
  backend/app/views/spree/admin/prices/_variant_prices.html.erb
  backend/app/views/spree/admin/prices/index.html.erb
  backend/app/views/spree/admin/shared/_product_tabs.html.erb
  backend/app/views/spree/admin/stores/_form.html.erb
  backend/config/routes.rb
  backend/spec/features/admin/configuration/stores_spec.rb
  backend/spec/features/admin/general_settings/prices_settings_presence_spec.rb
  backend/spec/features/admin/general_settings/prices_settings_updating_spec.rb
  backend/spec/features/admin/products/variant_prices_spec.rb
  core/app/controllers/spree/base_controller.rb
  core/app/models/spree/app_configuration.rb
  core/app/models/spree/line_item.rb
  core/app/models/spree/store.rb
  core/config/locales/en.yml
  core/db/migrate/20191017121054_add_supported_currencies_to_store.rb
  core/lib/spree/core.rb
  core/lib/spree/core/controller_helpers/currency_helpers.rb
  core/lib/spree/core/controller_helpers/store.rb
  core/lib/spree/permitted_attributes.rb
  core/lib/spree/testing_support/factories/store_factory.rb
  core/spec/lib/spree/core/controller_helpers/store_spec.rb
  core/spec/models/spree/line_item_spec.rb
  core/spec/models/spree/store_spec.rb
  frontend/app/assets/javascripts/spree/frontend/multi_currency.js
  frontend/app/controllers/spree/currency_controller.rb
  frontend/config/routes.rb
  frontend/spec/features/order_prices_spec.rb
  frontend/spec/features/product_prices_spec.rb
  frontend/spec/features/template_rendering_spec.rb
Labels: International :globe_with_meridians:

#10159 Add Customer Returns API v1 docs
  guides/src/content/api/customer_returns.md
  guides/src/data/customer_return.js
  guides/src/data/customer_returns.js
  guides/src/data/index.js
  guides/src/data/orders.js
  guides/src/data/payments.js
Labels: API, Documentation :book:

#10157 [SD-234] Adds compare at price editing for admin product prices tab
  backend/app/controllers/spree/admin/prices_controller.rb
  backend/app/views/spree/admin/prices/_variant_prices.html.erb
  backend/spec/features/admin/products/variant_prices_spec.rb
Labels: International :globe_with_meridians:

#10161 Add safeguard for scenarios where supported_currencies is nil
  backend/app/controllers/spree/admin/prices_controller.rb
Labels: International :globe_with_meridians:

#10155 Extensions tutorial: fix VariantDecorator example.
  guides/src/content/developer/tutorials/extensions_tutorial.md
Labels: Documentation :book:

#10167 Developing spree documentation enhancements
  README.md
  guides/src/content/developer/tutorials/developing_spree.md
  lib/sandbox.sh
Labels: Documentation :book:

#10178 Fixes checkout progress line
  frontend/app/assets/stylesheets/spree/frontend/views/spree/checkout/edit.scss
  frontend/app/helpers/spree/frontend_helper.rb
Labels: Bug, Storefront :shopping_cart:

#10197 [WCAG-4] Add aria-label attribute to affected links
  frontend/app/helpers/spree/frontend_helper.rb
  frontend/app/views/kaminari/twitter-bootstrap-4/_first_page.html.erb
  frontend/app/views/kaminari/twitter-bootstrap-4/_last_page.html.erb
  frontend/app/views/kaminari/twitter-bootstrap-4/_next_page.html.erb
  frontend/app/views/kaminari/twitter-bootstrap-4/_prev_page.html.erb
Labels: Accessibility

#10199 [WCAG-6] Fix aria-labelledby attr
  frontend/app/views/spree/products/_filters_mobile.html.erb
Labels: Accessibility

#10200 [WCAG-7] Use submit button instead of submit input
  frontend/app/views/spree/shared/_search.html.erb
  frontend/spec/features/products_spec.rb
Labels: Accessibility

#10198 [WCAG-5] Add aria-label attr to search input
  frontend/app/views/spree/shared/_search.html.erb
Labels: Accessibility

#10196 [WCAG-3] Optimize pagination svg icons in order to avoid id's collisions
  frontend/app/assets/images/pagination-arrow-right.svg
  frontend/app/assets/images/pagination-double-arrow-right.svg
Labels: Accessibility

#10156 Set Product Variant Via URL Query Parameter
  core/app/presenters/spree/variant_presenter.rb
  frontend/app/assets/javascripts/spree/frontend/views/spree/products/cart_form.js
  frontend/app/assets/javascripts/spree/frontend/views/spree/shared/variant_select.js
  frontend/spec/features/products_spec.rb
Labels: Storefront :shopping_cart:

#10177 Add new tutorial for basic product attribute extension
  guides/src/content/developer/tutorials/extend_product_attributes.md
Labels: Documentation :book:
