Repository spree/spree, pull requests merged in 2020-06, with the labels that each got.

#10202 [WCAG-9] AAU I can navigate the main menu using TAB key
  frontend/app/assets/javascripts/spree/frontend.js
  frontend/app/assets/javascripts/spree/frontend/main_nav_bar.js
  frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/main_nav_bar.scss
  frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/nav_bar.scss
  frontend/app/views/spree/shared/_main_nav_bar.html.erb
Labels: Accessibility

#10203 [WCAG-10] Add aria labels in checkout address step inputs
  frontend/app/helpers/spree/addresses_helper.rb
  frontend/app/views/spree/addresses/_form.html.erb
Labels: Accessibility

#10204 [WCAG-11] Wrap checkout footer content with footer tags
  frontend/app/views/spree/layouts/checkout.html.erb
Labels: Accessibility

#10205 [WCAG-12] Fix login form tabindex order
  frontend/app/assets/stylesheets/spree/frontend/components-custom/inputs.scss
  frontend/app/views/spree/checkout/registration.html.erb
  frontend/app/views/spree/shared/_login.html.erb
Labels: Accessibility

#10207 [WCAG-13][WCAG-14] Add focus indicator to radio buttons
  frontend/app/assets/stylesheets/spree/frontend/components-custom/inputs.scss
Labels: Accessibility

#10209 [WCAG-16] Make sort button and filters on PLP accessible and interactive
  frontend/app/assets/stylesheets/spree/frontend/views/spree/products/index.scss
  frontend/app/views/spree/products/_filters_desktop.html.erb
  frontend/app/views/spree/products/_sort_desktop.html.erb
Labels: Accessibility

#10208 [WCAG-15] Fix tabindex on checkout confirm page by removing flex order
  frontend/app/views/spree/checkout/_confirm.html.erb
  frontend/app/views/spree/checkout/_delivery_informations.html.erb
Labels: Accessibility

#10210 [WCAG-17] Fix choosing variants on PDP using keyboard
  frontend/app/assets/javascripts/spree/frontend/views/spree/products/cart_form.js
  frontend/app/assets/stylesheets/spree/frontend/views/spree/products/cart_form.scss
  frontend/app/views/spree/products/_color_option_type.html.erb
  frontend/app/views/spree/products/_option_type.html.erb
Labels: Accessibility

#10214 Fixes missing country picker flags
  frontend/app/assets/stylesheets/spree/frontend/flags/_variables.scss
Labels: Bug, Storefront :shopping_cart:

#10229 [SDP-303] Fixes problem with color picker on filters when OptionType has been translated
  frontend/app/views/spree/shared/_option_values.html.erb
Labels: Bug, Storefront :shopping_cart:

#10230 Changes country picker dropdown flag icon to globe
  frontend/app/assets/images/arrow-down.svg
  frontend/app/assets/images/global.svg
  frontend/app/views/spree/shared/_change_store.html.erb
Labels: Storefront :shopping_cart:

#10238 [SDP-304] Shows my account store credits in current currency
  core/app/models/concerns/spree/user_methods.rb
  frontend/app/views/spree/users/show.html.erb
Labels: Bug, Storefront :shopping_cart:

#10234 [SDP-303] Uses name instead of presentation parameter to compare
  core/app/models/spree/option_type.rb
  core/spec/models/spree/option_type_spec.rb
  frontend/app/views/spree/products/_filters_mobile.html.erb
Labels: Bug, Storefront :shopping_cart:

#10267 [WCAG-18] Fix main categories structure so user could see outline
  frontend/app/views/spree/home/index.html.erb
Labels: Accessibility

#10268 [WCAG-24] Add role navigation attribute
  frontend/app/views/spree/shared/_main_nav_bar.html.erb
  frontend/app/views/spree/shared/_mobile_navigation.html.erb
Labels: Accessibility

#10253 Feature: Order Notification Emails for Store Owner
  backend/app/controllers/spree/admin/stores_controller.rb
  backend/app/views/spree/admin/stores/_form.html.erb
  backend/spec/features/admin/configuration/stores_spec.rb
  core/app/mailers/spree/order_mailer.rb
  core/app/models/spree/order.rb
  core/app/models/spree/store.rb
  core/app/views/spree/order_mailer/store_owner_notification_email.html.erb
  core/app/views/spree/order_mailer/store_owner_notification_email.text.erb
  core/config/locales/en.yml
  core/db/migrate/20200607161221_add_store_owner_order_notification_delivered_to_spree_orders.rb
  core/db/migrate/20200607161222_add_new_order_notifications_email_to_spree_stores.rb
  core/lib/spree/permitted_attributes.rb
  core/lib/spree/testing_support/factories/store_factory.rb
  core/spec/mailers/order_mailer_spec.rb
  core/spec/models/spree/order_spec.rb
  guides/src/content/user/configuration/configuring_store_order_notifications.md
  guides/src/images/user/config/admin_stores_form_emails_group.png
  guides/src/images/user/config/admin_stores_index_edit_action_hlighted.png
Labels: New Feature :tada:

#10277 [WCAG-35] Open meganav submenu on focus
  frontend/app/assets/javascripts/spree/frontend/main_nav_bar.js
Labels: Accessibility

#10287 [WCAG-36] Fix duplicated icons/links
  frontend/app/assets/stylesheets/spree/frontend/application.scss
  frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/cart.scss
  frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/mobile_navigation.scss
  frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/nav_bar.scss
  frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/search_form.scss
  frontend/app/views/spree/shared/_cart.html.erb
  frontend/app/views/spree/shared/_link_to_cart.html.erb
  frontend/app/views/spree/shared/_mobile_navigation.html.erb
  frontend/app/views/spree/shared/_nav_bar.html.erb
  frontend/app/views/spree/shared/_search.html.erb
  frontend/spec/requests/cart_spec.rb
Labels: Accessibility

#10289 [WCAG-38] Add aria-label attribute to multiple navigation elementns
  frontend/app/views/spree/shared/_main_nav_bar.html.erb
  frontend/app/views/spree/shared/_mobile_navigation.html.erb
Labels: Accessibility

#10290 [WCAG-37] Fix Landmarks must be uniquely identifiable issue
  frontend/app/views/spree/shared/_breadcrumbs.html.erb
  frontend/app/views/spree/shared/_taxonomies.html.erb
Labels: Accessibility

#10291 Fix firefox bug for incorrect input width with display flex property
  frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/quantity_select.scss
  frontend/app/views/spree/products/_cart_form.html.erb
  frontend/app/views/spree/shared/_quantity_select.html.erb
Labels: Bug

#10284 [SDP-340] Fixes products in admin taxons displaying prices only in USD
  api/app/views/spree/api/v1/products/show.rabl
  backend/app/views/spree/admin/products/_autocomplete.js.erb
  backend/app/views/spree/admin/products/index.html.erb
  backend/spec/features/admin/products/products_spec.rb
Labels: Admin Panel ⚙️, Bug

#10294 [WCAG-39] Fix issues reported by axe tool on cart page
  core/config/locales/en.yml
  frontend/app/assets/javascripts/spree/frontend/main_nav_bar.js
  frontend/app/assets/stylesheets/spree/frontend/views/spree/orders/edit.scss
  frontend/app/helpers/spree/frontend_helper.rb
  frontend/app/views/spree/orders/_coupon_code.html.erb
  frontend/app/views/spree/orders/_line_item.html.erb
  frontend/app/views/spree/orders/_line_item_data.html.erb
  frontend/app/views/spree/shared/_main_nav_bar.html.erb
  frontend/app/views/spree/shared/_mobile_navigation.html.erb
Labels: Accessibility

#10292 [SDP-352] Fixes for mailer issues related to stores
  core/app/mailers/spree/base_mailer.rb
  core/app/models/spree/app_configuration.rb
  core/app/views/spree/shared/_base_mailer_header.html.erb
Labels: Bug

#10265 [SDP-343] Fixes multiple occurences of a product on admin products list search
  backend/app/views/spree/admin/products/index.html.erb
  backend/spec/features/admin/products/products_spec.rb
  core/app/models/spree/product.rb
  core/spec/models/spree/product/scopes_spec.rb
Labels: Admin Panel ⚙️, Bug

#10297 Fix Over Scroll In Admin
  backend/app/assets/stylesheets/spree/backend/components/_navbar.scss
  backend/app/assets/stylesheets/spree/backend/components/_tables.scss
  backend/app/views/spree/admin/orders/index.html.erb
  backend/app/views/spree/admin/payment_methods/index.html.erb
  backend/app/views/spree/admin/payments/index.html.erb
  backend/app/views/spree/admin/prices/_variant_prices.html.erb
  backend/app/views/spree/admin/products/index.html.erb
  backend/app/views/spree/admin/products/stock.html.erb
  backend/app/views/spree/admin/promotions/index.html.erb
  backend/app/views/spree/admin/reimbursement_types/index.html.erb
  backend/app/views/spree/admin/return_authorizations/_form.html.erb
  backend/app/views/spree/admin/return_authorizations/edit.html.erb
  backend/app/views/spree/admin/return_authorizations/index.html.erb
  backend/app/views/spree/admin/return_authorizations/new.html.erb
  backend/app/views/spree/admin/return_index/return_authorizations.html.erb
  backend/app/views/spree/admin/roles/index.html.erb
  backend/app/views/spree/admin/state_changes/index.html.erb
  backend/app/views/spree/admin/stores/index.html.erb
  backend/app/views/spree/admin/tax_rates/index.html.erb
  backend/spec/features/admin/configuration/payment_methods_spec.rb
Labels: Admin Panel ⚙️

#10298 [SDP-311] Order Confirmation page needs translation of months
  core/app/helpers/spree/base_helper.rb
  core/spec/helpers/base_helper_spec.rb
  frontend/app/views/spree/orders/show.html.erb
Labels: Storefront :shopping_cart:

#10301 [SDP-385] Fixes products carousel caching problem
  frontend/app/views/spree/shared/_carousel_4_products.html.erb
Labels: Bug, Storefront :shopping_cart:

#10302 Small Fixes
  backend/app/assets/images/backend-location.svg
  backend/app/assets/javascripts/spree/backend/stock_management.js
  backend/app/assets/javascripts/spree/backend/variant_management.js
  backend/app/assets/stylesheets/spree/backend/components/_buttons.scss
  backend/app/views/spree/admin/option_types/index.html.erb
  backend/app/views/spree/admin/product_properties/_product_property_fields.html.erb
  backend/app/views/spree/admin/product_properties/index.html.erb
  backend/app/views/spree/admin/products/_form.html.erb
  backend/app/views/spree/admin/return_index/customer_returns.html.erb
  backend/app/views/spree/admin/return_index/return_authorizations.html.erb
  backend/app/views/spree/admin/shared/_content_header.html.erb
  backend/app/views/spree/admin/shared/_index_table_options.html.erb
  backend/app/views/spree/admin/taxonomies/_list.html.erb
  backend/app/views/spree/admin/users/index.html.erb
Labels: Admin Panel ⚙️

#10303 Fix flash of old arrow in ransackable tables.
  backend/app/assets/javascripts/spree/backend/admin.js
  backend/app/assets/stylesheets/spree/backend/components/_buttons.scss
  backend/app/assets/stylesheets/spree/backend/components/_filters.scss
  backend/app/assets/stylesheets/spree/backend/components/_icons.scss
  backend/config/initializers/ransack.rb
Labels: Admin Panel ⚙️

#10305 Updates migrations with column_exists checks
  core/db/migrate/20200607161221_add_store_owner_order_notification_delivered_to_spree_orders.rb
  core/db/migrate/20200607161222_add_new_order_notifications_email_to_spree_stores.rb
Labels: Improvement

#10306 More Responsive Table fixes
  backend/app/helpers/spree/admin/navigation_helper.rb
  backend/app/views/spree/admin/adjustments/_adjustments_table.html.erb
  backend/app/views/spree/admin/countries/index.html.erb
  backend/app/views/spree/admin/customer_returns/_reimbursements_table.html.erb
  backend/app/views/spree/admin/customer_returns/_return_item_decision.html.erb
  backend/app/views/spree/admin/customer_returns/_return_item_selection.html.erb
  backend/app/views/spree/admin/customer_returns/index.html.erb
  backend/app/views/spree/admin/images/index.html.erb
  backend/app/views/spree/admin/log_entries/index.html.erb
  backend/app/views/spree/admin/option_types/edit.html.erb
  backend/app/views/spree/admin/option_types/index.html.erb
  backend/app/views/spree/admin/orders/_adjustments.html.erb
  backend/app/views/spree/admin/orders/_risk_analysis.html.erb
  backend/app/views/spree/admin/payments/_capture_events.html.erb
  backend/app/views/spree/admin/payments/_list.html.erb
  backend/app/views/spree/admin/payments/source_views/_gateway.html.erb
  backend/app/views/spree/admin/payments/source_views/_storecredit.html.erb
  backend/app/views/spree/admin/prices/_variant_prices.html.erb
  backend/app/views/spree/admin/product_properties/index.html.erb
  backend/app/views/spree/admin/promotion_categories/index.html.erb
  backend/app/views/spree/admin/properties/index.html.erb
  backend/app/views/spree/admin/prototypes/_prototypes.html.erb
  backend/app/views/spree/admin/prototypes/index.html.erb
  backend/app/views/spree/admin/reimbursements/edit.html.erb
  backend/app/views/spree/admin/reimbursements/index.html.erb
  backend/app/views/spree/admin/reimbursements/show.html.erb
  backend/app/views/spree/admin/reports/index.html.erb
  backend/app/views/spree/admin/reports/sales_total.html.erb
  backend/app/views/spree/admin/return_authorizations/index.html.erb
  backend/app/views/spree/admin/return_index/customer_returns.html.erb
  backend/app/views/spree/admin/shared/_order_summary.html.erb
  backend/app/views/spree/admin/shared/_refunds.html.erb
  backend/app/views/spree/admin/shared/_sidebar.html.erb
  backend/app/views/spree/admin/shared/named_types/_index.html.erb
  backend/app/views/spree/admin/shipping_categories/index.html.erb
  backend/app/views/spree/admin/shipping_methods/index.html.erb
  backend/app/views/spree/admin/states/_state_list.html.erb
  backend/app/views/spree/admin/stock_locations/index.html.erb
  backend/app/views/spree/admin/stock_movements/index.html.erb
  backend/app/views/spree/admin/stock_transfers/_stock_movements.html.erb
  backend/app/views/spree/admin/stock_transfers/index.html.erb
  backend/app/views/spree/admin/stock_transfers/new.html.erb
  backend/app/views/spree/admin/stock_transfers/show.html.erb
  backend/app/views/spree/admin/store_credit_categories/index.html.erb
  backend/app/views/spree/admin/store_credits/index.html.erb
  backend/app/views/spree/admin/tax_categories/index.html.erb
  backend/app/views/spree/admin/taxonomies/_list.html.erb
  backend/app/views/spree/admin/taxons/_taxon_table.html.erb
  backend/app/views/spree/admin/users/_lifetime_stats.html.erb
  backend/app/views/spree/admin/users/index.html.erb
  backend/app/views/spree/admin/users/items.html.erb
  backend/app/views/spree/admin/users/orders.html.erb
  backend/app/views/spree/admin/variants/index.html.erb
  backend/app/views/spree/admin/zones/index.html.erb
  backend/app/views/spree/layouts/admin.html.erb
Labels: Admin Panel ⚙️

#10309 [SDP-340] Fixes currency on variants list for product
  backend/app/views/spree/admin/variants/index.html.erb
  backend/spec/features/admin/products/edit/variants_spec.rb
  backend/spec/features/admin/products/variant_spec.rb
Labels: Admin Panel ⚙️, Bug
