Repository spree/spree, pull requests merged in 2021-05, with the labels that each got.

#10555 [SD-987] Add filtering products by properties
  backend/app/views/spree/admin/properties/_form.html.erb
  backend/app/views/spree/admin/properties/index.html.erb
  backend/spec/features/admin/properties/edit_property_spec.rb
  core/app/finders/spree/products/find.rb
  core/app/models/spree/product_property.rb
  core/app/models/spree/property.rb
  core/db/migrate/20201023152810_add_filterable_to_spree_properties.rb
  core/lib/spree/core/search/base.rb
  frontend/app/helpers/spree/frontend_helper.rb
  frontend/app/views/spree/products/_filters_desktop.html.erb
  frontend/app/views/spree/products/_filters_mobile.html.erb
  frontend/app/views/spree/products/index.html.erb
  frontend/app/views/spree/shared/_properties.html.erb
  frontend/spec/features/products_filtering_spec.rb
Labels: API, Admin Panel ⚙️, Storefront :shopping_cart:

#11006 Added Properties filtering to Storefront API
  api/app/serializers/spree/v2/storefront/product_property_serializer.rb
  api/docs/v2/storefront/index.yaml
  api/spec/requests/spree/api/v2/storefront/products_spec.rb
  backend/app/views/spree/admin/properties/index.html.erb
  core/app/finders/spree/products/find.rb
  core/app/models/concerns/spree/filter_param.rb
  core/app/models/spree/option_type.rb
  core/app/models/spree/product_property.rb
  core/app/models/spree/property.rb
  core/db/migrate/20210504163720_add_filter_param_to_spree_product_properties.rb
  core/db/migrate/20210505114659_add_filter_param_to_spree_properties.rb
  core/lib/spree/core.rb
  core/lib/spree/core/search/base.rb
  core/spec/models/spree/option_type_spec.rb
  core/spec/models/spree/product_property_spec.rb
  core/spec/models/spree/property_spec.rb
  core/spree_core.gemspec
  frontend/app/views/spree/products/_filters_desktop.html.erb
  frontend/app/views/spree/products/_filters_mobile.html.erb
  frontend/app/views/spree/shared/_properties.html.erb
  frontend/spec/features/products_filtering_spec.rb
Labels: API

#11007 [SD-1323] Allow filtering Products on PLP by a custom price range
  core/app/finders/spree/products/find.rb
  core/app/presenters/spree/filters/price.rb
  core/app/presenters/spree/filters/price_range.rb
  core/app/presenters/spree/filters/quantified_price_range.rb
  core/config/locales/en.yml
  core/lib/spree/core/search/base.rb
  core/spec/finders/spree/products/find_spec.rb
  core/spec/presenters/spree/filters/price_range_spec.rb
  core/spec/presenters/spree/filters/price_spec.rb
  core/spec/presenters/spree/filters/quantified_price_range_spec.rb
  frontend/app/assets/javascripts/spree/frontend.js
  frontend/app/assets/javascripts/spree/frontend/views/spree/products/index.js
  frontend/app/assets/javascripts/spree/frontend/views/spree/products/price_filters.es6
  frontend/app/helpers/spree/frontend_helper.rb
  frontend/app/helpers/spree/products_filters_helper.rb
  frontend/app/views/spree/products/_filters_desktop.html.erb
  frontend/app/views/spree/products/_filters_mobile.html.erb
  frontend/spec/features/products_spec.rb
Labels: Storefront :shopping_cart:

#11031 [SD-1101] Allow clearing all Filters on PLP
  frontend/app/helpers/spree/products_filters_helper.rb
  frontend/app/views/spree/products/_filters_desktop.html.erb
  frontend/app/views/spree/products/_filters_mobile.html.erb
  frontend/spec/features/products_filtering_spec.rb
Labels: Storefront :shopping_cart:

#11023 [SD-1326] Display only these Filters that have Products attached
  core/app/finders/concerns/spree/product_filterable.rb
  core/app/finders/spree/option_values/find_available.rb
  core/app/finders/spree/product_properties/find_available.rb
  core/app/models/concerns/spree/product_scopes.rb
  core/app/models/spree/option_value.rb
  core/app/models/spree/product_property.rb
  core/app/models/spree/property.rb
  core/app/presenters/spree/filters/options.rb
  core/app/presenters/spree/filters/properties.rb
  core/app/presenters/spree/filters/property.rb
  core/lib/spree/testing_support/factories/options_factory.rb
  core/lib/spree/testing_support/factories/property_factory.rb
  core/spec/finders/spree/option_values/find_available_spec.rb
  core/spec/finders/spree/product_properties/find_available_spec.rb
  core/spec/models/spree/product/scopes_spec.rb
  core/spec/models/spree/product_property_spec.rb
  core/spec/models/spree/property_spec.rb
  core/spec/presenters/spree/filters/options_spec.rb
  core/spec/presenters/spree/filters/properties_spec.rb
  core/spec/presenters/spree/filters/property_spec.rb
  frontend/app/helpers/spree/frontend_helper.rb
  frontend/app/views/spree/products/_filters_desktop.html.erb
  frontend/spec/features/products_filtering_spec.rb
Labels: Storefront :shopping_cart:

#11036 Fixed JS undefined errors when application does not use the updated 4…
  frontend/app/assets/javascripts/spree/frontend/currency.js
Labels: International :globe_with_meridians:, Storefront :shopping_cart:

#11037 [SD-1327] Fix issue with mixing Properties and Price filters
  frontend/app/assets/javascripts/spree/frontend/views/spree/products/price_filters.es6
  frontend/spec/features/products_filtering_spec.rb
Labels: Bug, Storefront :shopping_cart:

#11032 Fix Issue with menu changes not appearing because of Turbo Links
  api/app/controllers/spree/api/v2/storefront/menus_controller.rb
  backend/app/assets/javascripts/spree/backend.js
  backend/app/assets/javascripts/spree/backend/menus/menu.es6
  backend/app/views/spree/admin/menu_items/link_inputs/_url.html.erb
  core/app/models/spree/menu.rb
  core/app/models/spree/menu_item.rb
  core/config/locales/en.yml
  core/spec/models/spree/menu_item_spec.rb
  frontend/app/assets/stylesheets/spree/frontend/views/spree/shared/footer.scss
  frontend/app/helpers/spree/navigation_helper.rb
  frontend/app/views/spree/shared/_footer.html.erb
  frontend/app/views/spree/shared/_header.html.erb
  frontend/app/views/spree/shared/_main_nav_bar.html.erb
  frontend/app/views/spree/shared/_mobile_navigation.html.erb
  frontend/app/views/spree/shared/_nav_bar.html.erb
  frontend/spec/helpers/navigation_helper_spec.rb
  sample/db/samples/menu_items.rb
Labels: API, Admin Panel ⚙️, Storefront :shopping_cart:

#11035 [SD-1319] As a Admin in Admin Panel -> Store Edit I can upload a Store Favicon
  api/app/serializers/spree/v2/storefront/store_serializer.rb
  api/spec/requests/spree/api/v2/storefront/stores_spec.rb
  backend/app/controllers/spree/admin/stores_controller.rb
  backend/app/views/spree/admin/stores/_form.html.erb
  backend/spec/features/admin/configuration/stores_spec.rb
  backend/spec/fixtures/files/favicon.ico
  core/app/helpers/spree/base_helper.rb
  core/app/models/spree/store.rb
  core/config/locales/en.yml
  core/lib/spree/permitted_attributes.rb
  core/lib/spree/testing_support/factories/store_factory.rb
  core/spec/fixtures/favicon.ico
  core/spec/helpers/base_helper_spec.rb
  core/spec/models/spree/store_spec.rb
  frontend/app/views/spree/shared/_head.html.erb
  frontend/spec/features/template_rendering_spec.rb
  frontend/spec/fixtures/files/store_favicon.ico
Labels: Admin Panel ⚙️, Multi-Store 🏬, Storefront :shopping_cart:

#11042 [SD-1099] Fix caching of Option Values filters
  core/app/models/spree/option_value_variant.rb
  core/app/models/spree/variant.rb
  core/lib/spree/testing_support/factories/options_factory.rb
  core/spec/models/spree/option_value_variant_spec.rb
  core/spec/models/spree/variant_spec.rb
  frontend/app/helpers/spree/frontend_helper.rb
  frontend/app/views/spree/products/_filters_desktop.html.erb
  frontend/app/views/spree/shared/_option_values.html.erb
  frontend/spec/features/products_filtering_spec.rb
Labels: Bug, Storefront :shopping_cart:

#11049 Update authentication.md
  guides/src/content/developer/3_customization/authentication.md
Labels: Documentation :book:

#11048 Added more information about Serializer caching
  api/app/serializers/spree/api/v2/base_serializer.rb
Labels: Documentation :book:

#11055 [SD-1337] Validate Store favicon image properties
  backend/app/views/spree/admin/stores/_form.html.erb
  backend/spec/features/admin/configuration/stores_spec.rb
  backend/spec/fixtures/files/icon_512x512.png
  core/app/models/spree/store.rb
  core/config/locales/en.yml
  core/lib/spree/testing_support/factories/store_factory.rb
  core/spec/fixtures/files/icon_256x256.gif
  core/spec/fixtures/files/icon_256x256.png
  core/spec/fixtures/files/icon_512x512.png
  core/spec/fixtures/files/img_256x128.png
  core/spec/models/spree/store_spec.rb
Labels: Admin Panel ⚙️

#11002 allow user to change default addresses through API
  api/app/controllers/spree/api/v2/base_controller.rb
  api/app/controllers/spree/api/v2/storefront/account/addresses_controller.rb
  api/app/controllers/spree/api/v2/storefront/account_controller.rb
  api/app/models/spree/api_dependencies.rb
  api/config/routes.rb
  api/docs/v2/storefront/index.yaml
  api/spec/requests/spree/api/v2/storefront/account_spec.rb
  core/app/models/concerns/spree/user_address.rb
  core/app/models/spree/app_dependencies.rb
  core/app/services/spree/account/addresses/create.rb
  core/app/services/spree/account/addresses/helper.rb
  core/app/services/spree/account/create.rb
  core/app/services/spree/account/update.rb
  core/config/locales/en.yml
  core/lib/spree/permitted_attributes.rb
  core/spec/models/spree/user_spec.rb
  core/spec/services/spree/account/addresses/create_spec.rb
  core/spec/services/spree/account/create_spec.rb
  core/spec/services/spree/account/update_spec.rb
Labels: API, Storefront :shopping_cart:

#11047 [SD-987] Stop displaying duplicate Products on PLP when viewing by Taxon
  core/app/finders/spree/products/find.rb
  core/app/helpers/spree/products_helper.rb
  core/app/models/concerns/spree/product_scopes.rb
  core/lib/spree/testing_support/factories/classification_factory.rb
  core/spec/finders/spree/products/find_spec.rb
  core/spec/helpers/products_helper_spec.rb
  core/spec/models/spree/product/scopes_spec.rb
Labels: Bug, Storefront :shopping_cart:, WIP

#11063 [SD-1331] Assign Store to Payment Method factory
  api/spec/requests/spree/api/v2/storefront/checkout_spec.rb
  core/lib/spree/testing_support/factories/payment_method_factory.rb
Labels: Improvement

#11065 Fix filtering Products by Options
  api/spec/requests/spree/api/v2/storefront/products_spec.rb
  core/app/finders/spree/products/find.rb
  core/spec/finders/spree/products/find_spec.rb
Labels: API, Bug

#11080 Update documentation on Spree 3 to 4 migration
  guides/src/content/developer/4_advanced/existing_app_tutorial.md
  guides/src/content/developer/upgrades/four-dot-oh-to-four-dot-one.md
  guides/src/content/developer/upgrades/three-dot-seven-to-four-dot-oh.md
  guides/src/content/release_notes/4_0_0.md
  guides/src/content/release_notes/4_2_0.md
Labels: Documentation :book:
