Repository spree/spree, pull requests merged in 2021-08, with the labels that each got.

#11194 Platform API - Product & Variants serializers
  api/app/helpers/spree/api/v2/display_money_helper.rb
  api/app/serializers/spree/api/v2/platform/product_serializer.rb
  api/app/serializers/spree/api/v2/platform/stock_item_serializer.rb
  api/app/serializers/spree/api/v2/platform/stock_location_serializer.rb
  api/app/serializers/spree/api/v2/platform/tax_category_serializer.rb
  api/app/serializers/spree/api/v2/platform/variant_serializer.rb
  api/lib/spree/api/testing_support/v2/serializers_params.rb
  api/spec/requests/spree/api/v2/storefront/products_spec.rb
  api/spec/serializers/spree/api/v2/platform/product_serializer_spec.rb
  api/spec/serializers/spree/api/v2/platform/taxonomy_serializer_spec.rb
  api/spec/serializers/spree/api/v2/platform/variant_serializer_spec.rb
  api/spec/spec_helper.rb
  common_spree_dependencies.rb
  core/app/models/spree/variant.rb
Labels: API

#11189 Drop Promotion#code and path uniqueness validation
  backend/spec/controllers/spree/admin/promotions_controller_spec.rb
  core/app/models/spree/promotion.rb
  core/db/migrate/20210730154425_fix_promotion_code_and_path_unique_indexes.rb
  core/spec/models/spree/promotion_spec.rb
Labels: Multi-Store 🏬

#11192 Add CMS to release notes.
  guides/src/content/release_notes/4_3_0.md
Labels: Documentation :book:

#11054 SD-1297 - Add Documentation For Using Menus
  guides/src/content/user/navigation/add_menu_items.md
  guides/src/content/user/navigation/building_the_main_menu.md
  guides/src/content/user/navigation/creating_menus.md
  guides/src/content/user/navigation/index.md
  guides/src/images/user/navigation/categories.jpg
  guides/src/images/user/navigation/container_code.jpg
  guides/src/images/user/navigation/empty_menu_page.jpg
  guides/src/images/user/navigation/link_to.jpg
  guides/src/images/user/navigation/link_to_taxon_set.jpg
  guides/src/images/user/navigation/links_added.jpg
  guides/src/images/user/navigation/menu_items_area.jpg
  guides/src/images/user/navigation/new_menu.jpg
  guides/src/images/user/navigation/new_menu_item_page.jpg
  guides/src/images/user/navigation/women.jpg
Labels: Documentation :book:

#10592 [SD-1369] Enables user to remove credit card
  api/app/controllers/spree/api/v2/storefront/account/credit_cards_controller.rb
  api/app/models/spree/api_dependencies.rb
  api/config/routes.rb
  api/docs/v2/storefront/index.yaml
  api/spec/requests/spree/api/v2/storefront/account/credit_cards_spec.rb
  core/app/models/concerns/spree/user_payment_source.rb
  core/app/models/spree/ability.rb
  core/app/models/spree/app_dependencies.rb
  core/app/models/spree/credit_card.rb
  core/app/models/spree/payment.rb
  core/app/models/spree/payment_method.rb
  core/app/services/spree/credit_cards/destroy.rb
  core/config/locales/en.yml
  core/spec/models/spree/payment_method/store_credit_spec.rb
  core/spec/models/spree/payment_method_spec.rb
  core/spec/models/spree/payment_spec.rb
  core/spec/services/spree/credit_cards/destroy_spec.rb
  frontend/app/assets/javascripts/spree/frontend.js
  frontend/app/assets/javascripts/spree/frontend/checkout.js
  frontend/app/views/spree/checkout/_credit_card.html.erb
  frontend/app/views/spree/shared/_translations.html.erb
  frontend/spec/features/checkout_spec.rb
Labels: Storefront :shopping_cart:, API

#11225 User `Product.like_any` in Storefront Products API
  core/app/finders/spree/products/find.rb
Labels: API

#11245 Added universal collection caching for Platform/Storefront API
  .circleci/config.yml
  api/app/controllers/concerns/spree/api/v2/caching.rb
  api/app/controllers/spree/api/v2/resource_controller.rb
  api/app/controllers/spree/api/v2/storefront/account/orders_controller.rb
  api/app/models/spree/api_configuration.rb
  api/app/serializers/spree/api/v2/base_serializer.rb
  api/app/serializers/spree/api/v2/platform/product_serializer.rb
  api/app/serializers/spree/v2/storefront/product_serializer.rb
  api/spec/requests/spree/api/v2/caching_spec.rb
  common_spree_dependencies.rb
  core/lib/generators/spree/dummy/templates/rails/test.rb
  core/lib/spree/testing_support/rspec_retry_config.rb
Labels: API
